[project]
name = "newshackpack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy<2.0.0",
    "scikit-learn>=1.6.1",
    "torch<=2.2.2",
    "tqdm>=4.67.1",
    "transformers>=4.48.3",
]
